### PR TITLE
Update raop_client.c

### PR DESCRIPTION
**Pull request by josla972**
I get dual shairport hosts. One is IPV4 and the other one is IPV6. Whenever raop tries to connect to the IPV6 host, it crashes, and this happens frequently e.g. when I stop streaming. This ugly fix removes the IPV6 host and lets me stream audio flawlessly with IPV4 :).

### CODE REVIEW

**Comment by atcapollo** [comment]
This patch doesn't seem to work for me I still see duplicate hosts in pavucontrol.

**Comment by josla972** [comment]
And one host is IPV4 and the other one IPV6? Do you find "IPV6 is not supported!" in the log file?

**Comment by atcapollo** [comment]
Ubuntu ipv4 to apple airport express ipv6 and ipv4. I still see duplicate airport express in pavucontrol.

**Comment by atcapollo** [comment]
No I don't see the message in the log file. I cannot tell from pavucontrol which instance is which

**Comment by josla972** [comment]
Looking for :: is not airtight I guess. Try removing a colon. You also might want to run the debug lines I added unconditionally and see what differs between your two hosts in the log, i.e. replace the lines in my patch with the following and look for "Host: " in the log: 

pa_log_warn("Host: %s",host);

**Comment by atcapollo** [comment]
Will try it. Not getting any sound at the moment on any device since moving to xubuntu 14.04 so this refinement had little effect.

**Comment by josla972** [comment]
Making a new pull request with a better check for IPV6.

**Pull request closed without merging**
